### PR TITLE
test: fix flaking unit test and make functional tests more adaptable to different atsigns

### LINKED ISSUE #489: feat: check docker readiness
Docker readiness check programs should be written to check if the Docker virtual environment is ready for tests to be ran on it

image

Instead of sleeping, we should follow a similar pattern that is used in noports and at_client_sdk

### LINKED ISSUE #491: bug: flaking unit tests
I ran the unit tests back to back 5 times and the unit tests flaked once

image

https://github.com/atsign-foundation/at_c/actions/runs/12600305758

### LINKED ISSUE #492: test regression: atclient_find_atserver_address has false expectations when running outside of docker ve
The `FIRST_ATSIGN` argument is dynamically injected into the test at build time, but `EXPECTED_HOST` and `EXPECTED_PORT` are hard-coded to the ve atSign's host and port, which means the test will always fail outside of the virtual env.

```
#define EXPECTED_HOST "vip.ve.atsign.zone"
#define EXPECTED_PORT 25000
```

Maybe we can:
1. Disable the test (return 0) if the `FIRST_ATSIGN` doesn't match the ve one that we expect
2. If `FIRST_ATSIGN` doesn't match the ve atSign, we replace all 3 macro arguments with a well known prod atSign and it's host & port.

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
closes #492 
closes #491 
closes #489 

**- What I did**

Regarding `.github/workflows/tests.yaml`:
- Added `-VV` to unit tests
- Setting the test dir to the directory instead of using working-directory to make it easier to copy and paste it when testing locally
- Added `check_docker_readiness` program that checks if virtual environment has been started and also is PKAM ready.

Regarding `atclient.c`
- Fixed a segfault possibility if err_msg is NULL, then *err_msg is a seg fault.

Regarding `test_atkeys_write.c`
- Moved `test_atkeys_write.c` to functional tests since we test pkam authentication after reading and writing a key file
- Modified the code so that we could use VE atSigns

Regarding `tests/functional_tests/tools`:
- Removed it entirely and we now have `tests/functional_tests/virtualenv`

Regarding `tests/functional_tests`
- Removed `config.c` and moved the helper functions to `helpers.c`
- Moved `functional_tests_set_up_atkeys` to be in `helpers.c`
- Refactored test_atclient_pkam_authenticate to use refactored helper function `functional_tests_set_up_atkeys`

Regarding justfile stuff
- Added parameters to `just.template.env`
- Modified `configure-test-func` in `justfile`

Other changes
- Added `<getopt.h>` to `atactivate_arg_parser.c` cause I was getting an error in Ubuntu 22.04

**- How to verify it**

See this run: https://github.com/atsign-foundation/at_c/actions/runs/12645111162/job/35233754565?pr=490

**- Description for the changelog**
test: fix flaking unit test and make functional tests more adaptable to different atsigns

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
I was able to replicate the unit test flaking with verbose mode on here: https://github.com/atsign-foundation/at_c/actions/runs/12600442007/job/35119481513

**Comment by JeremyTubongbanua** [comment]
Looking closely at the test, we depend on the atSign @8incanteater to pkam authenticate. I'll move this test over to functional tests and use a virtual environment atSign

image

File: tests/functional_tests/tools/build.sh
Comment (XavierChanth) [inline tests/functional_tests/tools/build.sh:1]: The purpose of adding the justfile was to remove the need for bash scripts. Instead, please add the necessary parameters to the justfile and the `just.env` template file.

**Review by xavierchanth — CHANGES_REQUESTED** [review]
The purpose of adding the justfile in #483 was to remove the need for bash scripts. Instead, please add the necessary options to the cmake commands in the justfile and update the `just.env` template file (`just.template.env`) with the necessary environment variables that were added.

File: justfile [hunk 1]
```diff
@@ -96,11 +96,19 @@ configure-test-func:
   cmake -B $PWD/build/test-func -S $PWD \
     -DCMAKE_BUILD_TYPE=Debug \
     -DCMAKE_C_COMPILER=$C_COMPILER \
-    -DCMAKE_C_FLAGS="-std=c99 -Wno-error " \
+    -DCMAKE_C_FLAGS="-std=c99 -Wno-error" \
     -DATSDK_BUILD_TESTS="func" \
+    -DATSDK_BUILD_UNIT_TESTS=OFF \
+    -DATSDK_BUILD_FUNCTIONAL_TESTS=ON \
```
Comment (xavierchanth) [inline justfile]: These are no longer necessary. `-DATSDK_BUILD_TESTS="func"` is the correct way now.

The value can either be ON, OFF, "func" or "unit"

Comment (JeremyTubongbanua) [reply justfile]: Done in https://github.com/atsign-foundation/at_c/pull/490/commits/cb4ce8ceef8ec2135f5174749f41de179f8a25e4

**Comment by JeremyTubongbanua** [comment]
How I run the functional tests using virtual environment locally:

Prerequisites:
- just
- cmake
- gcc

1. First start the docker virtual environment locally by doing

```bash
cd tests/functional_tests/virtualenv
sudo ./start_virtualenv.sh
# wait 5 seconds
sudo ./pkam_virtualenv.sh
```

2. Create `just.env` in root of project and paste this:

```.env
C_COMPILER=gcc
ATDIRECTORY_HOST=vip.ve.atsign.zone
ATDIRECTORY_PORT=64
FIRST_ATSIGN=@alice🛠
FIRST_ATSIGN_ATSERVER_HOST=vip.ve.atsign.zone
FIRST_ATSIGN_ATSERVER_PORT=25000
SECOND_ATSIGN=@bob🛠
SECOND_ATSIGN_ATSERVER_HOST=vip.ve.atsign.zone
SECOND_ATSIGN_ATSERVER_PORT=25003
```

3. In the root of the project, run command 1 (for verbosity) or command 2 to just run it

command 1:

```bash
just configure-test-func build-test-func && ctest --test-dir ./build/test-func/tests/functional_tests/ -VV 
```

command 2:

```bash
just test-func
```

Output example from running `just test-func`

```
Test project /home/jeremy/GitHub/at_c/build/test-func
      Start  1: test_atclient_connection
 1/10 Test  #1: test_atclient_connection ....................   Passed   21.26 sec
      Start  2: test_atclient_get_atkeys
 2/10 Test  #2: test_atclient_get_atkeys ....................   Passed    0.12 sec
      Start  3: test_atclient_monitor
 3/10 Test  #3: test_atclient_monitor .......................   Passed    0.50 sec
      Start  4: test_atclient_notify
 4/10 Test  #4: test_atclient_notify ........................   Passed    0.13 sec
      Start  5: test_atclient_pkam_authenticate
 5/10 Test  #5: test_atclient_pkam_authenticate .............   Passed    0.24 sec
      Start  6: test_atclient_publickey
 6/10 Test  #6: test_atclient_publickey .....................   Passed    0.26 sec
      Start  7: test_atclient_selfkey
 7/10 Test  #7: test_atclient_selfkey .......................   Passed    0.13 sec
      Start  8: test_atclient_sharedkey
 8/10 Test  #8: test_atclient_sharedkey .....................   Passed    0.30 sec
      Start  9: test_atclient_utils_find_atserver_address
 9/10 Test  #9: test_atclient_utils_find_atserver_address ...   Passed    3.11 sec
      Start 10: test_atkeys_write
10/10 Test #10: test_atkeys_write ...........................   Passed    0.12 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) =  26.18 sec
jeremy@atsign:~/GitHub/at_c$ 
```

**Review by xavierchanth — DISMISSED** [review]

**Review by xavierchanth — APPROVED** [review]
